import { escapeHtml } from "@/lib/csv/sanitize";
import { formatINR, pct } from "@/lib/domain/cost";
import { formatIST } from "@/lib/domain/dates";
import { NDR_LABELS, type NdrReason } from "@/lib/domain/ndr";
import { DIM_LABELS, type DimKey } from "@/lib/analytics/types";
import { filtersToQuery } from "@/lib/analytics/filters";
import { asOfString, getCostModel, getDatasetById } from "@/lib/org";
import { getFinding } from "@/lib/findings";
import { listShipments } from "@/lib/shipments";
import { latestSimulationForFinding } from "@/lib/simulations";
import { getDashboard } from "@/lib/analytics/insights";
import { DISCLAIMER } from "@/lib/analytics/simulate";

export interface BuiltReport {
  title: string;
  markdown: string;
  html: string;
  json: unknown;
}

type ProfileRow = { key: string; shipments: number; eligible: number; rto: number; rtoValue: number };

function table(headers: string[], rows: string[][]): string {
  return [`| ${headers.join(" | ")} |`, `| ${headers.map(() => "---").join(" | ")} |`, ...rows.map((r) => `| ${r.map((c) => c.replace(/\|/g, "/")).join(" | ")} |`)].join("\n");
}

/** Minimal, safe Markdown → HTML for the constrained syntax this module emits. Everything is escaped first. */
export function markdownToHtml(md: string): string {
  const inline = (s: string) => escapeHtml(s).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/_(.+?)_/g, "<em>$1</em>");
  const lines = md.split("\n");
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const l = lines[i];
    if (l.startsWith("|")) {
      const block: string[] = [];
      while (i < lines.length && lines[i].startsWith("|")) block.push(lines[i++]);
      const cells = (row: string) => row.replace(/^\||\|$/g, "").split("|").map((c) => c.trim());
      const [head, , ...body] = block;
      out.push(`<table><thead><tr>${cells(head).map((c) => `<th>${inline(c)}</th>`).join("")}</tr></thead><tbody>${body.map((r) => `<tr>${cells(r).map((c) => `<td>${inline(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`);
      continue;
    }
    if (l.startsWith("### ")) out.push(`<h3>${inline(l.slice(4))}</h3>`);
    else if (l.startsWith("## ")) out.push(`<h2>${inline(l.slice(3))}</h2>`);
    else if (l.startsWith("# ")) out.push(`<h1>${inline(l.slice(2))}</h1>`);
    else if (l.startsWith("> ")) out.push(`<blockquote>${inline(l.slice(2))}</blockquote>`);
    else if (l.startsWith("- ")) {
      const items: string[] = [];
      while (i < lines.length && lines[i].startsWith("- ")) items.push(`<li>${inline(lines[i++].slice(2))}</li>`);
      out.push(`<ul>${items.join("")}</ul>`);
      continue;
    } else if (l.trim()) out.push(`<p>${inline(l)}</p>`);
    i++;
  }
  return out.join("\n");
}

export function wrapHtml(title: string, body: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>
body{font:14px/1.5 system-ui,sans-serif;color:#1a1a1a;max-width:860px;margin:32px auto;padding:0 16px}
h1{font-size:22px}h2{font-size:16px;border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:28px}
table{border-collapse:collapse;width:100%;margin:8px 0;font-size:13px}th,td{border:1px solid #ddd;padding:4px 8px;text-align:left}th{background:#f3f2ee}
blockquote{border-left:4px solid #b4442a;background:#fbf1ee;margin:12px 0;padding:8px 12px;font-weight:600}
@media print{body{margin:0}}</style></head><body>${body}</body></html>`;
}

function profileTable(label: string, rows: ProfileRow[] | undefined, dim: string): string {
  if (!rows?.length) return "";
  const nice = (k: string) => (dim === "ndrReason" ? NDR_LABELS[k as NdrReason] ?? k : k);
  return `### ${label}\n${table([label, "Resolved shipments", "RTOs", "RTO rate", "RTO value"], rows.map((r) => [nice(r.key), String(r.eligible), String(r.rto), r.eligible ? pct(r.rto / r.eligible) : "—", formatINR(r.rtoValue)]))}\n`;
}

export async function buildInvestigationReport(findingId: string, aiText?: { text: string; provider: string; model: string } | null): Promise<BuiltReport | null> {
  const f = await getFinding(findingId);
  if (!f) return null;
  const ds = await getDatasetById(f.datasetId);
  if (!ds) return null;
  const [cost, sim, sample] = await Promise.all([getCostModel(), latestSimulationForFinding(f.id), listShipments(ds.id, { ...f.filters, status: ["RTO"] }, 1, 10, "value")]);
  const ev = f.evidence as Record<string, any>;
  const md: string[] = [];
  md.push(`# ${f.code} — ${f.title}`);
  if (ds.isDemo) md.push(`> DEMO DATASET — synthetic data, not customer data.`);
  md.push(`**Dataset:** ${ds.name}  \n**Data as of:** ${asOfString(ds)}  \n**Status:** ${f.status ?? "Not yet investigated"}  \n**Severity:** ${f.severity}  \n**Generated:** ${formatIST(new Date())}`);
  md.push(`## Summary\n${ev.summary ?? ""}`);
  if (aiText) md.push(`_Narrative generated by ${aiText.provider} / ${aiText.model} from the structured evidence above; deterministic figures are authoritative._\n\n${aiText.text}`);

  md.push(`## Evidence`);
  if (ev.kind === "CONCENTRATION") {
    md.push((ev.candidate.reasons as string[]).map((r) => `- ${r}`).join("\n"));
    const c = ev.candidate;
    md.push(`\n**Scoring (transparent):** score ${c.score}/100 = 35% excess RTOs (${pct(c.components.excess, 0)}), 25% lift (${pct(c.components.lift, 0)}), 20% value share (${pct(c.components.value, 0)}), 10% sample size (${pct(c.components.sample, 0)}), 10% recurrence (${pct(c.components.recurrence, 0)}).`);
  } else if (ev.kind === "ANOMALY") {
    const a = ev.anomaly;
    md.push(`- Current 7-day RTO rate: ${pct(a.current.rate)} (n=${a.current.n}, RTOs=${a.current.rto})`);
    md.push(`- Baseline (prior ${a.baseline.weeks} weeks): ${pct(a.baseline.rate)}${a.baseline.minWeekRate !== null ? `, weekly range ${pct(a.baseline.minWeekRate)}–${pct(a.baseline.maxWeekRate)}` : ""}`);
    md.push(`- Ratio vs baseline: ${a.ratio?.toFixed(2)}×, z-score ${a.z?.toFixed(1)}`);
  }

  md.push(`## Affected shipments and value\n- Resolved shipments in segment: ${f.affectedShipments.toLocaleString("en-IN")}\n- RTO value affected: ${formatINR(f.affectedValue, false)}\n- Matching RTO shipments listed in explorer: ${sample.total.toLocaleString("en-IN")} (link: /shipments${filtersToQuery({ ...f.filters, status: ["RTO"] })})`);

  const g = (ev.profile?.groups ?? {}) as Record<string, ProfileRow[]>;
  const factors = [profileTable("Payment type", g.payment, "payment"), profileTable("Courier", g.courier, "courier"), profileTable("Category", g.category, "category"), profileTable("NDR reason", g.ndrReason, "ndrReason"), profileTable("Order value", g.valueBand, "valueBand"), profileTable("State", g.state, "state")].filter(Boolean);
  md.push(`## Relevant segments and contributing factors\n_Factors are associated with this segment; they are not proven causes._\n\n${factors.join("\n")}`);

  if (sample.rows.length) {
    md.push(`## Sample of affected shipments (highest value RTOs)\n${table(["Shipment", "Date", "Courier", "Pincode", "Payment", "Value", "Attempts", "NDR reason"], sample.rows.map((r) => [r.shipmentId, formatIST(r.orderDate, false), r.courier ?? "—", r.pincode ?? "—", r.payment, formatINR(r.value, false), String(r.attempts), r.ndrReason ? NDR_LABELS[r.ndrReason as NdrReason] ?? r.ndrReason : "—"]))}`);
  }

  if (sim) {
    const r = sim.result;
    md.push(`## Intervention simulation\n> SIMULATION — NOT A GUARANTEED OUTCOME\n\n**Scenario:** ${r.label}  \n**Target:** ${sim.target.description}\n\n${table(["", "RTO rate", "Est. RTO cost", "RTO value"], [["Current (observed)", pct(r.current.rtoRate), formatINR(r.current.rtoCost, false), formatINR(r.current.rtoValue, false)], ["Simulated estimate", pct(r.simulated.rtoRate), formatINR(r.simulated.rtoCost, false), formatINR(r.simulated.rtoValue, false)]])}\n\n- Estimated RTOs avoided: ${r.diff.rtoAvoided.toFixed(1)}\n- Estimated cost saved: ${formatINR(r.diff.costSaved, false)}\n- Estimated value recovered (GMV): ${formatINR(r.diff.valueRecovered, false)}\n- Program cost / lost margin: ${formatINR(r.diff.programCost, false)} / ${formatINR(r.diff.lostMargin, false)}\n- Estimated net benefit: ${formatINR(r.diff.netBenefit, false)}\n\n**Assumptions**\n${r.assumptions.map((a) => `- ${a}`).join("\n")}\n${r.warnings.length ? `\n**Warnings**\n${r.warnings.map((a) => `- ${a}`).join("\n")}` : ""}`);
  } else {
    md.push(`## Intervention simulation\nNo simulation has been saved for this finding yet. Use the Simulator to estimate the impact of a policy change.`);
  }

  md.push(`## Recommended investigation actions\n- ${f.suggestion ?? "Inspect the underlying shipments."}\n- Open the listed shipment timelines and compare NDR reasons across attempts.\n- Validate with the courier and ops team before changing policy; run any change on a small cohort first.`);
  if (f.notes.length) md.push(`## Investigation notes\n${f.notes.map((n) => `- ${formatIST(n.createdAt)} — ${n.body.replace(/\n/g, " ")}`).join("\n")}`);
  md.push(`## Method and caveats\nFindings are derived from deterministic analytics on imported shipment data (RTO rate = RTO ÷ resolved shipments; cost model: ₹${cost.forwardCost} forward + ₹${cost.reverseCost} reverse + ₹${cost.handlingCost} handling + write-off). Patterns are associations in historical data and do not establish causation. ${DISCLAIMER}`);

  const markdown = md.join("\n\n") + "\n";
  return { title: `${f.code} ${f.title}`, markdown, html: wrapHtml(f.title, markdownToHtml(markdown)), json: { finding: { id: f.id, code: f.code, title: f.title, status: f.status, severity: f.severity, evidence: f.evidence, filters: f.filters, affectedValue: f.affectedValue, affectedShipments: f.affectedShipments }, dataset: { id: ds.id, name: ds.name, isDemo: ds.isDemo }, simulation: sim, sampleShipments: sample.rows, notes: f.notes } };
}

export async function buildDatasetReport(datasetId: string): Promise<BuiltReport | null> {
  const ds = await getDatasetById(datasetId);
  if (!ds) return null;
  const cost = await getCostModel();
  const d = await getDashboard(ds, asOfString(ds), cost);
  const m = d.metrics;
  const md: string[] = [`# RTO Autopsy — Dataset summary`];
  if (ds.isDemo) md.push(`> DEMO DATASET — synthetic data, not customer data.`);
  md.push(`**Dataset:** ${ds.name}  \n**Data as of:** ${asOfString(ds)}  \n**Data quality score:** ${ds.qualityScore ?? "—"}/100`);
  md.push(`## Headline numbers\n${table(["Metric", "Value"], [["Total shipments", m.shipments.toLocaleString("en-IN")], ["Resolved shipments", m.eligible.toLocaleString("en-IN")], ["RTO rate", pct(m.rtoRate)], ["COD RTO rate", pct(m.codRtoRate)], ["Prepaid RTO rate", pct(m.prepaidRtoRate)], ["NDR rate", pct(m.ndrRate)], ["RTO value", formatINR(m.rtoValue, false)], ["Estimated RTO cost", formatINR(m.rtoCost, false)], ["Estimated recoverable value", formatINR(m.recoverableValue, false)]])}`);
  md.push(`## Anomalies (last 7 days vs prior 8 weeks)\n${d.anomalies.length ? d.anomalies.map((a) => `- ${a.label}: ${pct(a.result.current.rate)} vs baseline ${pct(a.result.baseline.rate)} (${a.result.ratio?.toFixed(1)}×, n=${a.result.current.n})`).join("\n") : "No statistically unusual change detected."}`);
  md.push(`## Top investigation candidates\n${d.candidates.length ? d.candidates.map((c) => `- **${c.label}** — score ${c.score}; ${c.reasons.slice(0, 3).join("; ")}`).join("\n") : "None met the sample-size and significance gates."}`);
  md.push(`## Method and caveats\nDeterministic analytics; associations only, not causal claims. Definitions are in docs/ANALYTICS_SPEC.md. Columns present in ${DIM_LABELS.courier.toLowerCase()} / pincode / product dimensions depend on the imported file.`);
  const markdown = md.join("\n\n") + "\n";
  void (null as unknown as DimKey);
  return { title: "Dataset summary", markdown, html: wrapHtml("Dataset summary", markdownToHtml(markdown)), json: { dataset: ds, metrics: m, anomalies: d.anomalies, candidates: d.candidates } };
}
