"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Alert, buttonClass } from "./ui";

interface Note {
  id: number;
  body: string;
  createdAt: string;
}

const STATUSES = ["OPEN", "INVESTIGATING", "RESOLVED", "DISMISSED"];

export function FindingActions({ findingId, investigationId, status, notes, aiConfigured }: { findingId: string; investigationId: string | null; status: string | null; notes: Note[]; aiConfigured: boolean }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [note, setNote] = useState("");
  const [ai, setAi] = useState<{ text?: string; label?: { provider: string; model: string }; message?: string } | null>(null);

  async function post(body: unknown) {
    setBusy(true);
    setError("");
    try {
      const res = await fetch(`/api/findings/${findingId}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data?.error?.message ?? "Request failed");
      return data;
    } catch (e) {
      setError(e instanceof Error ? e.message : "Request failed");
      return null;
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="space-y-4">
      {error && <Alert tone="bad" title="Could not complete the action">{error}</Alert>}
      {!investigationId ? (
        <div>
          <p className="mb-2 text-[13px] text-muted">This finding is not yet tracked. Open an investigation to assign a status and record notes.</p>
          <button className={buttonClass("primary")} disabled={busy} onClick={async () => { if (await post({ action: "investigate" })) router.refresh(); }}>
            {busy ? "Opening…" : "Open investigation"}
          </button>
        </div>
      ) : (
        <>
          <div className="flex flex-wrap items-end gap-3">
            <div>
              <label htmlFor="inv-status" className="mb-1 block text-[11px] font-semibold uppercase tracking-wider text-muted">Status</label>
              <select id="inv-status" className="rounded border border-line bg-panel px-2 py-1.5 text-[13px]" value={status ?? "OPEN"} disabled={busy} onChange={async (e) => { if (await post({ action: "status", status: e.target.value })) router.refresh(); }}>
                {STATUSES.map((s) => <option key={s}>{s}</option>)}
              </select>
            </div>
          </div>
          <form
            onSubmit={async (e) => {
              e.preventDefault();
              if (!note.trim()) return;
              if (await post({ action: "note", body: note })) {
                setNote("");
                router.refresh();
              }
            }}
          >
            <label htmlFor="inv-note" className="mb-1 block text-[11px] font-semibold uppercase tracking-wider text-muted">Add a note</label>
            <textarea id="inv-note" rows={3} maxLength={4000} value={note} onChange={(e) => setNote(e.target.value)} className="w-full rounded border border-line bg-panel px-2 py-1.5 text-[13px]" placeholder="What did you check? What did the courier say?" />
            <button type="submit" className={`${buttonClass("secondary", "sm")} mt-2`} disabled={busy || !note.trim()}>Save note</button>
          </form>
          <ul className="space-y-2" aria-label="Investigation notes">
            {notes.length === 0 && <li className="text-[13px] text-muted">No notes yet.</li>}
            {notes.map((n) => (
              <li key={n.id} className="rounded border border-line-soft bg-canvas px-3 py-2 text-[13px]">
                <p className="whitespace-pre-wrap">{n.body}</p>
                <p className="mt-1 text-[11px] text-muted">{new Date(n.createdAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</p>
              </li>
            ))}
          </ul>
        </>
      )}
      <div className="border-t border-line-soft pt-3">
        <button className={buttonClass("ghost", "sm")} disabled={busy} onClick={async () => { const d = await post({ action: "summarize" }); if (d) setAi(d.ai ? { text: d.text, label: d.label } : { message: d.message }); }}>
          {aiConfigured ? "Generate AI narrative (optional)" : "AI narrative (not configured)"}
        </button>
        {ai?.message && <p role="status" className="mt-2 text-[13px] text-muted">{ai.message}</p>}
        {ai?.text && (
          <div className="mt-2 rounded border border-link/30 bg-link-soft px-3 py-2 text-[13px]">
            <p className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-link">Generated by {ai.label?.provider} / {ai.label?.model} — narrative only; figures above are authoritative</p>
            <p>{ai.text}</p>
          </div>
        )}
      </div>
    </div>
  );
}
